// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktkla2nZ1REng3c3ZyfoVzpG7Z1zbvBo',
    appId: '1:410771624147:web:bc10043fbadf1ee8a74426',
    messagingSenderId: '410771624147',
    projectId: 'sbkzbailas',
    authDomain: 'sbkzbailas.firebaseapp.com',
    storageBucket: 'sbkzbailas.appspot.com',
    measurementId: 'G-SV1400G1YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_S1BFnZvtQ6pPfqx5ghlx0l-7feK0IA',
    appId: '1:410771624147:android:43ccedb4f0ac1c6aa74426',
    messagingSenderId: '410771624147',
    projectId: 'sbkzbailas',
    storageBucket: 'sbkzbailas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEO6lQu5rgNw732DQiu_refXbDXt-Eng0',
    appId: '1:410771624147:ios:40f84c9ae3f55dbfa74426',
    messagingSenderId: '410771624147',
    projectId: 'sbkzbailas',
    storageBucket: 'sbkzbailas.appspot.com',
    iosClientId: '410771624147-18gpph97latjnspub7dd516k4q6aism5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbkBailas',
  );
}
